const NOTIFICATION_TYPES = {
    SINGLE_BRAND: 'SINGLE_BRAND',
    SINGLE_OFFER: 'SINGLE_OFFER',
    SINGLE_STORE: 'SINGLE_STORE',
    SINGLE_CATEGORY: 'SINGLE_CATEGORY',
    FAVOURITES: 'FAVOURITES',
}

export default NOTIFICATION_TYPES;